### PR TITLE
fix: use proper PNG compression in ScreenshotKeysHighlighter

### LINKED ISSUE #3534: Anthropic API 400 error: image exceeds 5MB
**Describe the bug**
When clicking on a translation key in the editor, the Machine Translation panel shows an error from the AI Translator (Anthropic API). The translation does not load and a 400 error is displayed.

**To Reproduce**
Go to the Tolgee project itself
Open the translation editor
Click on the key organization_role_type_OWNER_hint
Open the Machine Translation panel
See error from AI Translator

**Expected behavior**
The AI Translator should generate a translation suggestion instead of showing an API error. 

**Screenshots**

Image

**Versions and environment**
Environment: Tolgee Cloud
Browser: Safari

**Additional context**
The error message indicates the request to the Anthropic API fails because the image payload exceeds the 5 MB limit

### PR DESCRIPTION
**Pull request by bdshadow**
ScreenshotKeysHighlighter.highlightKeys() was re-encoding images with compressionQuality=1.0f (no deflation), inflating a ~140KB stored image to ~12MB. This exceeded Anthropic's 5MB image limit. The issue affected all screenshots sent to LLMs, not just ones with highlight positions.

Changed compressionQuality from 1.0f to 0.8f, matching the quality used everywhere else (ImageConverter.getImage/getThumbnail).

Closes #3534

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved image compression to better control screenshot file sizes while preserving quality.
  * Highlighting now only applied when explicit key positions are present, avoiding unnecessary processing or altered outputs.

* **Tests**
  * Added tests ensuring highlighted and non-highlighted screenshots stay within the 5MB API size limit across scenarios.

### CODE REVIEW

**Comment by bdshadow** [comment]
@coderabbitai please review

File: ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt [hunk 1]
```diff
@@ -0,0 +1,189 @@
...
+      storedBytes.size,
+      outputBytes.size,
+      String.format("%.1f", outputBytes.size.toDouble() / storedBytes.size),
+    )
+
+    assertThat(outputBytes.size)
+      .withFailMessage(
+        "Re-encoded image (%d bytes) exceeds the 5 MB API limit even though " +
+          "nothing was highlighted. Stored image was only %d bytes (ratio: %.1fx). " +
+          "ScreenshotKeysHighlighter.highlightKeys() re-encodes with compressionQuality=1.0f.",
```
Comment (dkrizan) [inline ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt]: should not be `compressionQuality=1.0f` ? in `log.info` above is the same value

File: ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+      storedBytes.size,
+      highlightedBytes.size,
+      String.format("%.1f", highlightedBytes.size.toDouble() / storedBytes.size),
+    )
+
+    assertThat(highlightedBytes.size)
+      .withFailMessage(
+        "Highlighted image (%d bytes) exceeds the 5 MB API limit. " +
+          "Stored image was only %d bytes (ratio: %.1fx). " +
+          "ScreenshotKeysHighlighter.highlightKeys() re-encodes with compressionQuality=1.0f.",
```
Comment (dkrizan) [inline ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt]: same as above

File: ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt (hunk 1 above)
Comment (bdshadow) [reply ee/backend/tests/src/test/kotlin/io/tolgee/ee/unit/ScreenshotKeysHighlighterTest.kt]: i just removed this line
