### PR TITLE
perf: fix O(n) CPU spike in BatchJobChunkExecutionQueue with large queues

### LINKED ISSUE #3480: Performance issue: Batch job processing stalled with 115K pending chunks filling the queue
**Describe the bug**
When we deployed Tolgee v3.158.0 in production: 

- No batch jobs were being processed despite chunks being queued
- The internal queue accumulated 115,000 pending elements
- CPU usage maxed out, suggesting all CPU time was spent iterating through the massive queue rather than processing actual work

The batch job chunk execution queue was loading ALL pending chunks without any limit. When thousands of chunks accumulated, the system spent all its resources just traversing the queue instead of executing jobs.

**To Reproduce**
Have a tolgee instance with more than 150 000 pending elements to translate (with LLM) on a single project.

**Screenshots**
Image
Image

**Versions and environment**
- Tolgee Platform version: v3.158.0

**Notes**
We did a [fix](https://github.com/RakutenFrance/tolgee-platform/commit/65d63a29317722b920ba8cfddce387e07b00b972) that reintroduces the `chunkQueuePopulationSize` configuration (originally from PR https://github.com/tolgee/tolgee-platform/pull/3265, commit https://github.com/RakutenFrance/tolgee-platform/commit/90904f02f57ea98ba5c9b0a8ded8a5d1e840d608) which:

- Limits query results using `setMaxResults()
`- Adds a configurable cap (default: 1000) on chunks fetched per scheduled run
- Prevents queue bloat and restores processing capability

### PR DESCRIPTION
**Pull request by Jbbouille**
## Why

Observed via `tolgee.batch.job.execution.queue.size` metric: when the queue reached 110k+ items under high concurrency (10+ slots), CPU spiked and batch processing slowed to a crawl. Three O(n) scans fired on every polling cycle:

- `pollRoundRobin()` scanned the entire flat queue to find the next eligible job — O(n × concurrency) per iteration
- Micrometer scraped `ConcurrentLinkedQueue.size()` which is O(n)
- `logger.trace()` eagerly built a `joinToString` of all 110k items even when trace logging was disabled

## How

Replaced the flat `ConcurrentLinkedQueue` with a per-job indexed structure:

- `Map<JobId, ConcurrentLinkedDeque<ExecutionQueueItem>>` for O(1) per-job item access
- `ConcurrentLinkedDeque<Long>` for round-robin job ordering
- `ConcurrentHashMap.newKeySet()` for O(1) duplicate detection (replaces the O(n) queue snapshot)
- `AtomicInteger` for O(1) size tracking

`pollRoundRobin()` now does `pollFirst() + compute() + addLast()` — O(1) regardless of total queue size. Performance regression tests verify that 1 000 polls over a 110k-item queue complete in < 500ms and that poll time does not scale with queue size.

---

Supersedes #3511.
Closes #3480.

---

@JanCizmar you were right — adding a limit on the queue size was a hack that was hiding a real performance issue. This fixes the root cause instead.

## Summary by CodeRabbit

* **New Features**
  * Fair round‑robin scheduling across jobs for batch execution
  * Per‑job queues with O(1) duplicate detection and size tracking

* **Bug Fixes**
  * More reliable job removal and consistent queue state after concurrent mutations
  * More accurate runtime metrics for queue size reporting

* **Tests**
  * Added performance and regression tests validating large‑scale queue behavior and throughput

* **Chores**
  * Internal queue optimizations for O(1) enqueue/dequeue/contains/size operations

### CODE REVIEW

File: backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt [hunk 1]
```diff
@@ -65,19 +79,52 @@ class BatchJobChunkExecutionQueue(
...
+                decrementCharacterCount(item.jobCharacter)
+                totalSize.decrementAndGet()
+              }
+              if (deque.isEmpty()) {
+                roundRobinOrder.remove(item.jobId)
+                null
+              } else {
+                deque
+              }
+            }
```
[the remark this answers is not in the document]
Comment (bdshadow) [reply backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt]: looks like this is still a valid remark. @coderabbitai, am i right?

File: backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt [hunk 2]
```diff
@@ -183,125 +209,120 @@ class BatchJobChunkExecutionQueue(
...
+          decrementCharacterCount(item.jobCharacter)
+        }
+        removedCount = deque.size
+        totalSize.addAndGet(-removedCount)
       }
+      null // remove entry from map
+    }
+    if (removedCount > 0) {
+      // O(n) on roundRobinOrder, but removeJobExecutions is only called on cancellation
+      roundRobinOrder.remove(jobId)
```
Comment (bdshadow) [inline backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt]: looks like there is a race between `compute()` (line 218) returning and `roundRobinOrder.remove()`, a concurrent `addSingleItem()` for the same jobId can create a new deque and add the jobId to roundRobinOrder. I think `roundRobinOrder.remove()` should be moved inside the `compute`.

File: backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt [hunk 3]
```diff
@@ -183,125 +209,120 @@ class BatchJobChunkExecutionQueue(
...
-    for (i in jobIds.indices) {
-      val jobIndex = (startIndex + i) % jobIds.size
-      val targetJobId = jobIds[jobIndex]
-
-      // Find first item for this job and try to remove it
-      val item = queue.firstOrNull { it.jobId == targetJobId }
-      if (item != null && queue.remove(item)) {
-        // Successfully removed - update state and return
+      if (item != null) {
+        queuedExecutionIds.remove(item.chunkExecutionId)
```
Comment (bdshadow) [inline backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt]: same possible race condition here. Probably must be moved to the `compute` call

File: backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueueTest.kt [hunk 4]
```diff
@@ -0,0 +1,269 @@
+package io.tolgee.batch
+
+import io.micrometer.core.instrument.simple.SimpleMeterRegistry
+import io.tolgee.Metrics
+import io.tolgee.batch.data.ExecutionQueueItem
+import io.tolgee.batch.data.QueueEventType
+import io.tolgee.batch.events.JobQueueItemsEvent
+import io.tolgee.component.UsingRedisProvider
+import io.tolgee.configuration.tolgee.BatchProperties
```
Comment (bdshadow) [inline backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueueTest.kt]: please, remove unused import

File: backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt [hunk 5]
```diff
@@ -0,0 +1,217 @@
+package io.tolgee.batch
+
+import io.micrometer.core.instrument.simple.SimpleMeterRegistry
+import io.tolgee.Metrics
+import io.tolgee.batch.data.ExecutionQueueItem
+import io.tolgee.component.UsingRedisProvider
+import io.tolgee.configuration.tolgee.BatchProperties
```
Comment (bdshadow) [inline backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt]: please, remove unused import

**Review by bdshadow — CHANGES_REQUESTED** [review]

File: backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt [hunk 6]
```diff
@@ -0,0 +1,217 @@
...
+  fun `pollRoundRobin is fast with 1 large job and 110k items`() {
+    val items = (1L..110_000L).map { makeItem(it, jobId = 1L) }
+    executionQueue.addItemsToLocalQueue(items)
+
+    val polls = 1_000
+    val start = System.currentTimeMillis()
+    repeat(polls) { executionQueue.pollRoundRobin() }
+    val elapsedMs = System.currentTimeMillis() - start
+
+    println(
```
Comment (bdshadow) [inline backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt]: please replace `println` with logging in tests, it will be quieter in CI

File: backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt [hunk 7]
```diff
@@ -0,0 +1,217 @@
...
+   * With the old O(n) implementation, 1000 polls took several seconds.
+   * With the new O(1) structure, they must complete in under 500ms.
+   */
+  @Test
+  fun `pollRoundRobin is fast with 1 large job and 110k items`() {
+    val items = (1L..110_000L).map { makeItem(it, jobId = 1L) }
+    executionQueue.addItemsToLocalQueue(items)
+
+    val polls = 1_000
+    val start = System.currentTimeMillis()
```
Comment (bdshadow) [inline backend/data/src/test/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueuePerformanceTest.kt]: measuring execution time can be done with builtIn kotlin function: https://kotlinlang.org/docs/time-measurement.html

File: backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt [hunk 8]
```diff
@@ -65,19 +78,51 @@ class BatchJobChunkExecutionQueue(
...
+      val deque =
+        existing ?: ConcurrentLinkedDeque<ExecutionQueueItem>().also {
+          // Called atomically inside compute — only once per new job
+          roundRobinOrder.addLast(jobId)
+        }
+      deque.addLast(item)
+      deque
+    }
+
+    incrementCharacterCount(item.jobCharacter)
```
Comment (bdshadow) [inline backend/data/src/main/kotlin/io/tolgee/batch/BatchJobChunkExecutionQueue.kt]: Lines 100 and 101 should also be moved inside the `compute` to avoid inconsistency under race conditions.

**Review by bdshadow — CHANGES_REQUESTED** [review]

**Comment by Jbbouille** [comment]
I forgot to format it; sorry about that. It's done now.

**Review by bdshadow — APPROVED** [review]
